services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7
    ports:
      - "6379:6379"